version: "3"
services:
  slack-bridge:
    image: matrixdotorg/matrix-appservice-slack:latest
    restart: on-failure
    volumes:
      - ./config:/config
    networks:
      - matrix_net

  slack-bridge_db:
    image: postgres:14-alpine
    volumes:
      - slack-bridge-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=slack_bridge
      - POSTGRES_USER=slackbridge_user
      - POSTGRES_PASSWORD=${PG_SLACK_BRIDGE_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    networks:
      - matrix_net

volumes:
  slack-bridge-db:

networks:
  matrix_net:
    external: true
