version: "3"
services:
  discord-bridge:
    image: halfshot/matrix-appservice-discord:develop
    volumes:
      - ./matrix-appservice-discord:/data
    ports:
      - 9005:9005
    networks:
      - matrix_net

networks:
  matrix_net:
    external: true
